// <auto-generated />
using System;
using Cattobot.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cattobot.Db.Migrations
{
    [DbContext(typeof(CattobotDbContext))]
    [Migration("20260110104303_AddTmdbIndex")]
    partial class AddTmdbIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cattobot.Db.Models.FilmDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Actors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Countries")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Directors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.Property<bool>("IsSeries")
                        .HasColumnType("boolean");

                    b.Property<int?>("KinopoiskId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SearchIndex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TmdbLastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WikidataId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WikidataLastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SearchIndex");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchIndex"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchIndex"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("Cattobot.Db.Models.FilmGuildDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("uuid");

                    b.Property<int>("FilmStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("StatusOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "FilmId")
                        .IsUnique();

                    b.ToTable("FilmGuilds");
                });

            modelBuilder.Entity("Cattobot.Db.Models.FilmGuildMemberDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FilmGuildId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("FilmGuildId");

                    b.HasIndex("UserId");

                    b.ToTable("FilmGuildMembers");
                });

            modelBuilder.Entity("Cattobot.Db.Models.FilmGuildDb", b =>
                {
                    b.HasOne("Cattobot.Db.Models.FilmDb", "Film")
                        .WithMany("Guilds")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Cattobot.Db.Models.FilmGuildMemberDb", b =>
                {
                    b.HasOne("Cattobot.Db.Models.FilmGuildDb", null)
                        .WithMany("Members")
                        .HasForeignKey("FilmGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cattobot.Db.Models.FilmDb", b =>
                {
                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("Cattobot.Db.Models.FilmGuildDb", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
